name: libertyseg
recipe: acquia
config:
  via: apache:2.4
  webroot: docroot
  database: 'mariadb:10.1'
  composer_version: 2.0.7
  acli_version: latest
  ah_application_uuid: e70f25f2-4526-475a-b7f9-ee68a0cd6668
  ah_site_group: libertyseg
  php: '8.1'
  conf:
    php: php.ini
proxy:
  appserver:
    - libertyseg.lndo.site
    - sponsors.lndo.site
  phpmyadmin:
    - phpmyadmin.lndo.site
services:
  # The database service used for the `sponsors` site.
  sponsors:
    type: mariadb:10.3
    portforward: true
    creds:
      user: drupal
      password: drupal
      database: sponsors
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - sponsors
