version: 1.3.0

services:
  # mysql is supported from version: 1.0.0
  - mysql
  # custom php version is supported from version: 1.1.0
  - php:
      version: 8.1
  - composer:
      version: 2

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin

events:
  build:
    steps:
      - setup:
          type: script
          script:
            - composer validate --no-check-all --ansi
            - composer install
