<?php

/**
 * @file
 * Hook and preprocess custom lib_microsites.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\StreamWrapper\PublicStream;
use Drupal\file\Entity\File;

/**
 * Implements hook_entity_presave().
 */
function lib_microsites_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'landing_page':
    case 'landing_html':
      $public_path = PublicStream::basePath();

      // Check if folder exists and create if doesn't.
      if (!is_dir($public_path . '/microsites')) {
        mkdir('public://microsites');
      }

      // Load paragraph.
      if ($paragraph_field_items = $entity->get('field_p_components')->getValue()) {
        $paragraph_storage = \Drupal::entityTypeManager()->getStorage('paragraph');
        // Get paragraph field's ids.
        $ids = array_column($paragraph_field_items, 'target_id');

        // Load all paragraph objects.
        $paragraphs_objects = $paragraph_storage->loadMultiple($ids);
        foreach ($paragraphs_objects as $paragraph) {
          if ($paragraph->getParagraphType()->id == 'microsite') {
            // Get file field.
            $zip_fid = $paragraph->get('field_file_zip')->target_id;

            // Load file entity.
            $file = File::load($zip_fid);

            // Get file name witou extension.
            $name = str_replace(['.zip', '.ZIP'], '', $file->getFilename());
            $name = preg_replace('/_(\d+)/i', '', $name);
            $name = $zip_fid . '-' . \str_replace(' ', '', $name);

            // Real path of file.
            $path = \Drupal::service('file_system')->realpath($file->getFileUri());

            // Check if folder exists.
            if (is_dir($public_path . '/microsites/' . $name)) {
              rmdir('public://microsites/' . $name);
            }

            // Unzip on folder.
            $zip = new \ZipArchive();
            $zip->open($path);
            $zip->extractTo($public_path . '/microsites/' . $name);
            $zip->close();
            // Save microsite path.
            $paragraph->set('field_path', $public_path . '/microsites/' . $name . '/index.html');
            $paragraph->save();
          }
        }
      }
      break;
  }
}
