import PropTypes from 'prop-types'
import { SelectField } from './selectField'
import ToolTip from './toolTip'

const countryList = {
  'Colombia': 'Colombia',
  'Andorra': 'Andorra',
  'Emiratos Árabes Unidos': 'Emiratos Árabes Unidos',
  'Afganistán': 'Afganistán',
  'Antigua y Barbuda': 'Antigua y Barbuda',
  'Anguila': 'Anguila',
  'Albania': 'Albania',
  'Armenia': 'Armenia',
  'Antillas Neerlandesas': 'Antillas Neerlandesas',
  'Angola': 'Angola',
  'Antártida': 'Antártida',
  'Argentina': 'Argentina',
  'Samoa Americana': 'Samoa Americana',
  'Austria': 'Austria',
  'Australia': 'Australia',
  'Aruba': 'Aruba',
  'Islas Áland': 'Islas Áland',
  'Azerbaiyán': 'Azerbaiyán',
  'Bosnia y Herzegovina': 'Bosnia y Herzegovina',
  'Barbados': 'Barbados',
  'Bangladesh': 'Bangladesh',
  'Bélgica': 'Bélgica',
  'Burkina Faso': 'Burkina Faso',
  'Bulgaria': 'Bulgaria',
  'Bahréin': 'Bahréin',
  'Burundi': 'Burundi',
  'Benin': 'Benin',
  'San Bartolomé': 'San Bartolomé',
  'Bermudas': 'Bermudas',
  'Brunéi': 'Brunéi',
  'Bolivia': 'Bolivia',
  'Brasil': 'Brasil',
  'Bahamas': 'Bahamas',
  'Bhután': 'Bhután',
  'Isla Bouvet': 'Isla Bouvet',
  'Botsuana': 'Botsuana',
  'Belarús': 'Belarús',
  'Belice': 'Belice',
  'Canadá': 'Canadá',
  'Islas Cocos': 'Islas Cocos',
  'República Centro-Africana': 'República Centro-Africana',
  'Congo': 'Congo',
  'Suiza': 'Suiza',
  'Costa de Marfil': 'Costa de Marfil',
  'Islas Cook': 'Islas Cook',
  'Chile': 'Chile',
  'Camerún': 'Camerún',
  'China': 'China',
  'Costa Rica': 'Costa Rica',
  'Cuba': 'Cuba',
  'Cabo Verde': 'Cabo Verde',
  'Islas Christmas': 'Islas Christmas',
  'Chipre': 'Chipre',
  'República Checa': 'República Checa',
  'Alemania': 'Alemania',
  'Yibuti': 'Yibuti',
  'Dinamarca': 'Dinamarca',
  'Domínica': 'Domínica',
  'República Dominicana': 'República Dominicana',
  'Argel': 'Argel',
  'Ecuador': 'Ecuador',
  'Estonia': 'Estonia',
  'Egipto': 'Egipto',
  'Sahara Occidental': 'Sahara Occidental',
  'Eritrea': 'Eritrea',
  'España': 'España',
  'Etiopía': 'Etiopía',
  'Finlandia': 'Finlandia',
  'Fiji': 'Fiji',
  'Islas Malvinas': 'Islas Malvinas',
  'Micronesia': 'Micronesia',
  'Islas Faroe': 'Islas Faroe',
  'Francia': 'Francia',
  'Gabón': 'Gabón',
  'Reino Unido': 'Reino Unido',
  'Granada': 'Granada',
  'Georgia': 'Georgia',
  'Guayana Francesa': 'Guayana Francesa',
  'Guernsey': 'Guernsey',
  'Ghana': 'Ghana',
  'Gibraltar': 'Gibraltar',
  'Groenlandia': 'Groenlandia',
  'Gambia': 'Gambia',
  'Guinea': 'Guinea',
  'Guadalupe': 'Guadalupe',
  'Guinea Ecuatorial': 'Guinea Ecuatorial',
  'Grecia': 'Grecia',
  'Georgia del Sur e Islas Sandwich del Sur': 'Georgia del Sur e Islas Sandwich del Sur',
  'Guatemala': 'Guatemala',
  'Guam': 'Guam',
  'Guinea-Bissau': 'Guinea-Bissau',
  'Guayana': 'Guayana',
  'Hong Kong': 'Hong Kong',
  'Islas Heard y McDonald': 'Islas Heard y McDonald',
  'Honduras': 'Honduras',
  'Croacia': 'Croacia',
  'Haití': 'Haití',
  'Hungría': 'Hungría',
  'Indonesia': 'Indonesia',
  'Irlanda': 'Irlanda',
  'Israel': 'Israel',
  'Isla de Man': 'Isla de Man',
  'India': 'India',
  'Territorio Británico del Océano Índico': 'Territorio Británico del Océano Índico',
  'Irak': 'Irak',
  'Irán': 'Irán',
  'Islandia': 'Islandia',
  'Italia': 'Italia',
  'Jersey': 'Jersey',
  'Jamaica': 'Jamaica',
  'Jordania': 'Jordania',
  'Japón': 'Japón',
  'Kenia': 'Kenia',
  'Kirguistán': 'Kirguistán',
  'Camboya': 'Camboya',
  'Kiribati': 'Kiribati',
  'Comoros': 'Comoros',
  'San Cristóbal y Nieves': 'San Cristóbal y Nieves',
  'Corea del Norte': 'Corea del Norte',
  'Corea del Sur': 'Corea del Sur',
  'Kuwait': 'Kuwait',
  'Islas Caimán': 'Islas Caimán',
  'Kazajstán': 'Kazajstán',
  'Laos': 'Laos',
  'Líbano': 'Líbano',
  'Santa Lucía': 'Santa Lucía',
  'Liechtenstein': 'Liechtenstein',
  'Sri Lanka': 'Sri Lanka',
  'Liberia': 'Liberia',
  'Lesotho': 'Lesotho',
  'Lituania': 'Lituania',
  'Luxemburgo': 'Luxemburgo',
  'Letonia': 'Letonia',
  'Libia': 'Libia',
  'Marruecos': 'Marruecos',
  'Mónaco': 'Mónaco',
  'Moldova': 'Moldova',
  'Montenegro': 'Montenegro',
  'Madagascar': 'Madagascar',
  'Islas Marshall': 'Islas Marshall',
  'Macedonia': 'Macedonia',
  'Mali': 'Mali',
  'Myanmar': 'Myanmar',
  'Mongolia': 'Mongolia',
  'Macao': 'Macao',
  'Martinica': 'Martinica',
  'Mauritania': 'Mauritania',
  'Montserrat': 'Montserrat',
  'Malta': 'Malta',
  'Mauricio': 'Mauricio',
  'Maldivas': 'Maldivas',
  'Malawi': 'Malawi',
  'México': 'México',
  'Malasia': 'Malasia',
  'Mozambique': 'Mozambique',
  'Namibia': 'Namibia',
  'Nueva Caledonia': 'Nueva Caledonia',
  'Níger': 'Níger',
  'Islas Norkfolk': 'Islas Norkfolk',
  'Nigeria': 'Nigeria',
  'Nicaragua': 'Nicaragua',
  'Países Bajos': 'Países Bajos',
  'Noruega': 'Noruega',
  'Nepal': 'Nepal',
  'Nauru': 'Nauru',
  'Niue': 'Niue',
  'Nueva Zelanda': 'Nueva Zelanda',
  'Omán': 'Omán',
  'Panamá': 'Panamá',
  'Perú': 'Perú',
  'Polinesia Francesa': 'Polinesia Francesa',
  'Papúa Nueva Guinea': 'Papúa Nueva Guinea',
  'Filipinas': 'Filipinas',
  'Pakistán': 'Pakistán',
  'Polonia': 'Polonia',
  'San Pedro y Miquelón': 'San Pedro y Miquelón',
  'Islas Pitcairn': 'Islas Pitcairn',
  'Puerto Rico': 'Puerto Rico',
  'Palestina': 'Palestina',
  'Portugal': 'Portugal',
  'Islas Palaos': 'Islas Palaos',
  'Paraguay': 'Paraguay',
  'Qatar': 'Qatar',
  'Reunión': 'Reunión',
  'Rumanía': 'Rumanía',
  'Serbia y Montenegro': 'Serbia y Montenegro',
  'Rusia': 'Rusia',
  'Ruanda': 'Ruanda',
  'Arabia Saudita': 'Arabia Saudita',
  'Islas Solomón': 'Islas Solomón',
  'Seychelles': 'Seychelles',
  'Sudán': 'Sudán',
  'Suecia': 'Suecia',
  'Singapur': 'Singapur',
  'Santa Elena': 'Santa Elena',
  'Eslovenia': 'Eslovenia',
  'Islas Svalbard y Jan Mayen': 'Islas Svalbard y Jan Mayen',
  'Eslovaquia': 'Eslovaquia',
  'Sierra Leona': 'Sierra Leona',
  'San Marino': 'San Marino',
  'Senegal': 'Senegal',
  'Somalia': 'Somalia',
  'Surinam': 'Surinam',
  'Santo Tomé y Príncipe': 'Santo Tomé y Príncipe',
  'El Salvador': 'El Salvador',
  'Siria': 'Siria',
  'Suazilandia': 'Suazilandia',
  'Islas Turcas y Caicos': 'Islas Turcas y Caicos',
  'Chad': 'Chad',
  'Territorios Australes Franceses': 'Territorios Australes Franceses',
  'Togo': 'Togo',
  'Tailandia': 'Tailandia',
  'Tanzania': 'Tanzania',
  'Tayikistán': 'Tayikistán',
  'Tokelau': 'Tokelau',
  'Timor-Leste': 'Timor-Leste',
  'Turkmenistán': 'Turkmenistán',
  'Túnez': 'Túnez',
  'Tonga': 'Tonga',
  'Turquía': 'Turquía',
  'Trinidad y Tobago': 'Trinidad y Tobago',
  'Tuvalu': 'Tuvalu',
  'Taiwán': 'Taiwán',
  'Ucrania': 'Ucrania',
  'Uganda': 'Uganda',
  'Estados Unidos de América': 'Estados Unidos de América',
  'Uruguay': 'Uruguay',
  'Uzbekistán': 'Uzbekistán',
  'Ciudad del Vaticano': 'Ciudad del Vaticano',
  'San Vicente y las Granadinas': 'San Vicente y las Granadinas',
  'Venezuela': 'Venezuela',
  'Islas Vírgenes Británicas': 'Islas Vírgenes Británicas',
  'Islas Vírgenes de los Estados Unidos de América': 'Islas Vírgenes de los Estados Unidos de América',
  'Vietnam': 'Vietnam',
  'Vanuatu': 'Vanuatu',
  'Wallis y Futuna': 'Wallis y Futuna',
  'Samoa': 'Samoa',
  'Yemen': 'Yemen',
  'Mayotte': 'Mayotte',
  'Sudáfrica': 'Sudáfrica',
}

const SelectCountry = ({ handleChange }) => {
  return (
    <div className="form-item js-form-type-select form-type-select form__input--activo">
      <label htmlFor="SSP_PaisEvento__c">Selecciona el país del evento</label>
      <SelectField
        name="SSP_PaisEvento__c"
        defaultValue="Colombia"
        optionList={countryList}
        //required={true}
        handleChange={handleChange}
      />
      <ToolTip
        id="PaisEvento"
        text="País en donde ocurrió el evento o servicio"
      />
    </div>
  )
}

SelectCountry.propTypes = {
  handleChange: PropTypes.func,
}

export { SelectCountry }
