<?php

/**
 * @file
 * Contains lib_v2_questions_frequent.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lib_v2_questions_frequent_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the lib_v2_questions_frequent module.
        case 'help.page.lib_v2_questions_frequent':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Drop-down tabs with text') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_theme().
 */
function lib_v2_questions_frequent_theme()
{
    return [
        'lib_v2_questions_frequent' => [
            'render element' => 'children',
        ],
    ];
}

/**
 * Implements hook_theme_suggestions_block_alter().
 */
function lib_v2_questions_frequent_theme_suggestions_block_alter(array &$suggestions, array $variables, $hook)
{
    if (isset($variables['elements']['content']['#block_content'])) {
        array_splice($suggestions, 1, 0, 'block__' . $variables['elements']['content']['#block_content']->bundle());
    }
}

function lib_v2_questions_frequent_preprocess_paragraph(&$variables)
{
    /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
    $paragraph = $variables['paragraph'];
    // Get the type
    $parentBundle = $paragraph->bundle();

    if ("lib_v2_questions_frequent" == $parentBundle) {
        foreach ($paragraph->get('field_lib_v2_group_ref')->getValue() as $clave => $element) {
            $p = \Drupal\paragraphs\Entity\Paragraph::load($element['target_id']);
            $variables['questions_frequent'][$clave]['title'] = $p->field_lib_v2_group_ref_title->getValue()[0]['value'];
            
            $variables['questions_frequent'][$clave]['desc'] = $p->field_lib_v2_group_ref_descripti->getValue()[0]['value'];
        }
    }

}
