<?php

/**
 * @file
 * Contains lib_components_v4.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_help().
 */
function lib_components_v4_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lib_components_v4 module.
    case 'help.page.lib_components_v4':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('version 3 for liberty components') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function lib_components_v4_theme() {
  return [
    'lib_components_v4' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_block_alter().
 */
function lib_components_v4_theme_suggestions_block_alter(array &$suggestions, array $variables, $hook) {
  if (isset($variables['elements']['content']['#paragraph'])) {
    array_splice($suggestions, 1, 0, 'block__' . $variables['elements']['content']['#paragraph']->bundle());
  }
}

/**
 * Lib components v4 preprocess paragraph.
 */
function lib_components_v4_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];
  // Get the type.
  $parentBundle = $paragraph->bundle();

  if ("lib_v4_cards_group" == $parentBundle) {

    $variables['card_group4']['columns'] = 'grid-' . $paragraph->get('field_lib_v4_cards_group_ref')->getValue()[0]['value'];
    foreach ($paragraph->get('field_lib_v4_cards_group_r')->getValue() as $clave => $element) {
      $p = Paragraph::load($element['target_id']);
      $variables['card_group4']['items'][$clave]['title'] = $p->field_lib_v4_cards_title->getValue()[0]['value'];
      $variables['card_group4']['items'][$clave]['desc'] = $p->field_lib_v4_cards_desc->getValue()[0]['value'];
      $fid = $p->field_lib_v4_cards_image->getValue()[0]['target_id'];
      $media = Media::load($fid);
      $fid = $media->getSource()->getSourceFieldValue($media);
      $file = File::load($fid);
      $variables['card_group4']['items'][$clave]['imagen'] = file_create_url($file->getFileUri());
      $variables['card_group4']['items'][$clave]['link']['uri'] = $p->field_lib_v4_cards_link->getValue()[0]['uri'];
      $variables['card_group4']['items'][$clave]['link']['text'] = $p->field_lib_v4_cards_link->getValue()[0]['title'];
    }
  }
  if ("lib_v4_contacts_group" == $parentBundle) {

    foreach ($paragraph->get('field_lib_v4_contacts_group_ref')->getValue() as $clave => $element) {
      $p = Paragraph::load($element['target_id']);
      $variables['contact']['items'][$clave]['title'] = $p->field_lib_v4_contacts_title->getValue()[0]['value'];
      $variables['contact']['items'][$clave]['contact'] = $p->field_lib_v4_contacts_contact->getValue()[0]['value'];
      $fid = $p->field_lib_v4_contacts_image->getValue()[0]['target_id'];
      $media = Media::load($fid);
      $fid = $media->getSource()->getSourceFieldValue($media);
      $file = File::load($fid);
      $variables['contact']['items'][$clave]['imagen'] = file_create_url($file->getFileUri());
    }
  }
  if ("lib_v4_moreinfo_group" == $parentBundle) {

    foreach ($paragraph->get('field_lib_v4_moreinfo_group_ref')->getValue() as $clave => $element) {
      $p = Paragraph::load($element['target_id']);
      $variables['moreinfo']['items'][$clave]['title'] = $p->field_lib_v4_cardinfo_title->getValue()[0]['value'];
      $variables['moreinfo']['items'][$clave]['aux'] = $p->field_lib_v4_cardinfo_text_sup->getValue()[0]['value'];
      $variables['moreinfo']['items'][$clave]['link']['uri'] = $p->field_lib_v4_cardinfo_link->getValue()[0]['uri'];
      $variables['moreinfo']['items'][$clave]['link']['text'] = $p->field_lib_v4_cardinfo_link->getValue()[0]['title'];
    }
  }
  if ("lib_v4_carousel" == $parentBundle) {
    foreach ($paragraph->get('field_lib_v4_carousel_group_ref')->getValue() as $clave => $element) {
      $p = Paragraph::load($element['target_id']);
      $variables['card_carrusel4'][$clave]['subheading'] = $p->field_lib_v4_carousel_sec->getValue()[0]['value'];
      $variables['card_carrusel4'][$clave]['title'] = $p->field_lib_v4_carousel_text_main->getValue()[0]['value'];
      $variables['card_carrusel4'][$clave]['background'] = $p->field_lib_v4_carousel_background->getValue()[0]['value'];
      $variables['card_carrusel4'][$clave]['link']['uri'] = $p->field_lib_v4_carousel_link->getValue()[0]['uri'];
      $variables['card_carrusel4'][$clave]['link']['text'] = $p->field_lib_v4_carousel_link->getValue()[0]['title'];
      $variables['card_carrusel4'][$clave]['link']['color'] = $p->field_lib_v4_carousel_link_color->getValue()[0]['value'];
      $fid = $p->field_lib_v4_carousel_image->getValue()[0]['target_id'];
      $media = Media::load($fid);
      $fid = $media->getSource()->getSourceFieldValue($media);
      $file = File::load($fid);
      $variables['card_carrusel4'][$clave]['imagen'] = file_create_url($file->getFileUri());
    }
  }
}
