<?php

/**
 * @file
 * Contains lib_category_box_v2.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;

/**
 * Implements hook_help().
 */
function lib_category_box_v2_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the lib_category_box_v2 module.
        case 'help.page.lib_category_box_v2':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Caja de categorias v2') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_theme().
 */
function lib_category_box_v2_theme()
{
    return [
        'lib_category_box_v2' => [
            'render element' => 'children',
        ],
    ];
}

/**
 * Implements hook_theme_suggestions_block_alter().
 */
function lib_category_box_v2_theme_suggestions_block_alter(array &$suggestions, array $variables, $hook)
{
    if (isset($variables['elements']['content']['#block_content'])) {
        array_splice($suggestions, 1, 0, 'block__' . $variables['elements']['content']['#block_content']->bundle());
    }
}

function lib_category_box_v2_preprocess_paragraph(&$variables)
{
    /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
    $paragraph = $variables['paragraph'];
    // Get the type
    $parentBundle = $paragraph->bundle();
    if ("lib_v2_categorybox" == $parentBundle) {
        foreach ($paragraph->get('field_lib_v2_categorybox_group_r')->getValue() as $clave => $element) {
            $p = \Drupal\paragraphs\Entity\Paragraph::load($element['target_id']);
            $variables['categorybox'][$clave]['title'] = $p->field_lib_v2_categtabs_title->getValue()[0]['value'];
            $fid = $p->field_lib_v2_categtabs_icons->getValue()[0]['target_id'];
            $media = Media::load($fid);
            $fid = $media->getSource()->getSourceFieldValue($media);
            $file = File::load($fid);
            $variables['categorybox'][$clave]['logo'] = file_create_url($file->getFileUri());
            $variables['categorybox'][$clave]['column'] = $p->field_lib_v2_categtabs_colum->getValue()[0]['value'];

            foreach ($p->get('field_lib_v2_categtabs_group_ref')->getValue() as $key => $value) {
                $q = \Drupal\paragraphs\Entity\Paragraph::load($value['target_id']);
                $variables['categorybox'][$clave]['card'][$key]['desc'] = $q->field_lib_v2_categcard_desc->getValue()[0]['value'];
                $fid = $q->field_lib_v2_categcard_icon->getValue()[0]['target_id'];
                $media = Media::load($fid);
                $fid = $media->getSource()->getSourceFieldValue($media);
                $file = File::load($fid);
                $variables['categorybox'][$clave]['card'][$key]['icon'] = file_create_url($file->getFileUri());

            }

        }

    }
}
