<?php

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function lib_red_medica_theme($existing, $type, $theme, $path) {
  return [
    'medical_network' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_uninstall().
 */
function lib_red_medica_uninstall() {
  \Drupal::configFactory()->getEditable('lib_red_medical.settings')->delete();
}
