<?php

/**
 * @file
 * Contains liberty_claims.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function liberty_claims_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the liberty_claims module.
    case 'help.page.liberty_claims':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Consult of policies module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Theme.
 */
function liberty_claims_theme($existing, $type, $theme, $path) {
  return [
    'notification-mail' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'download_pdf' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function liberty_claims_mail($key, &$message, $params) {
  global $base_root, $base_path;

  switch ($params['subject']) {
    case 'Liberty Seguros | Tu siniestro ha sido radicado':
      $from = \Drupal::config('system.site')->get('mail');

      $message['headers']['MIME-Version'] = '1.0';
      $message['headers']['Content-Type'] = 'multipart/mixed;';
      $message['headers']['Reply-To'] = $params['name'] . '<' . $params['email'] . '>';
      $message['headers']['From'] = $message['headers']['Sender'] = $from;
      $message['subject'] = $params['subject'];

      $theme_body = [
        '#theme' => 'notification-mail',
        '#data' => [
          'url' => $base_root . $base_path . drupal_get_path('module', 'liberty_claims'),
          'name' => $params['name'],
          'document' => $params['document'],
          'plate' => $params['plate'],
          'claimType' => $params['claimType'],
          'number' => $params['number'],
          'date' => date('d / m / Y'),
        ],
      ];

      $message['body'][] = \Drupal::service('renderer')->render($theme_body);

      break;

    case 'Error radicacion Iaxis':

      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject2'];
      $message['body'][] = $params['message'];

      break;

    case 'Error radicacion Sipo':

      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject2'];
      $message['body'][] = $params['message'];

      break;
  }

}

/**
 * Function cron custom.
 */
function liberty_claims_cron() {
  $date = date("Y-m-d H:i:s");
  $file_system = \Drupal::service('file_system');
  $dateMonth = strtotime('-1 months', strtotime($date));
  $files = \Drupal::entityTypeManager()
    ->getStorage('file')
    ->getQuery()
    ->condition('uri', '%claimfiles%', 'LIKE')
    ->condition('created', $dateMonth, '<')
    ->range(0, 1000)
    ->execute();
  $storage_handler = \Drupal::entityTypeManager()->getStorage("file");

  foreach ($files as $file) {
    $locale_directory = $storage_handler->load($file)->get('uri')->getValue()[0]['value'];
    $directory = explode('/', $locale_directory);
    array_pop($directory);
    $uri = $directory[0] . '//' . $directory[2] . '/' . $directory[3];
    if (is_dir($uri)) {
      if (!$file_system->scanDirectory($uri, '/.*/')) {
        $file_system->rmdir($uri);
      }
    }

  }
  $entities = $storage_handler->loadMultiple($files);
  $storage_handler->delete($entities);

}
