<?php

/**
 * @file
 * Contains liberty_claims.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function liberty_claims_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the liberty_claims module.
    case 'help.page.liberty_claims':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Consult of policies module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Theme.
 */
function liberty_claims_theme($existing, $type, $theme, $path) {
  return [
    'notification-mail' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'download_pdf' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function liberty_claims_mail($key, &$message, $params) {
  global $base_root, $base_path;

  switch ($params['subject']) {
    case 'Liberty Seguros | Tu siniestro ha sido radicado':
      $from = \Drupal::config('system.site')->get('mail');

      $message['headers']['MIME-Version'] = '1.0';
      $message['headers']['Content-Type'] = 'multipart/mixed;';
      $message['headers']['Reply-To'] = $params['name'] . '<' . $params['email'] . '>';
      $message['headers']['From'] = $message['headers']['Sender'] = $from;
      $message['subject'] = $params['subject'];

      $theme_body = [
        '#theme' => 'notification-mail',
        '#data' => [
          'url' => $base_root . $base_path . \Drupal::service('extension.list.module')->getPath('liberty_claims'),
          'name' => $params['name'],
          'document' => $params['document'],
          'plate' => $params['plate'],
          'claimType' => $params['claimType'],
          'number' => $params['number'],
          'date' => date('d / m / Y'),
        ],
      ];

      $message['body'][] = \Drupal::service('renderer')->render($theme_body);

      break;

    case 'Error radicacion Iaxis':
    case 'Error radicacion Sipo':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8\r\n';
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject2'];
      $message['body'][] = $params['message'];

      break;

    default:
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8\r\n';
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }

}

/**
 * Function cron custom.
 */
function liberty_claims_cron() {
  $date = date("Y-m-d H:i:s");
  $file_system = \Drupal::service('file_system');
  $dateMonth = strtotime('-1 months', strtotime($date));
  $files = \Drupal::entityTypeManager()
    ->getStorage('file')
    ->getQuery()
    ->condition('uri', '%claimfiles%', 'LIKE')
    ->condition('created', $dateMonth, '<')
    ->range(0, 1000)
    ->execute();
  $storage_handler = \Drupal::entityTypeManager()->getStorage("file");

  foreach ($files as $file) {
    $locale_directory = $storage_handler->load($file)->get('uri')->getValue()[0]['value'];
    $directory = explode('/', $locale_directory);
    array_pop($directory);
    $uri = $directory[0] . '//' . $directory[2] . '/' . $directory[3];
    if (is_dir($uri) && !$file_system->scanDirectory($uri, '/.*/')) {
      $file_system->rmdir($uri);
    }

  }
  $entities = $storage_handler->loadMultiple($files);
  $storage_handler->delete($entities);
}

/**
 * Implements hook_token_info().
 */
function liberty_claims_token_info() {
  $info = [];
  $info['types']['liberty_claims'] = [
    'name' => t('Custom Token for Liberty Claims'),
    'description' => t('A custom token for CKEditor in Liberty Claims module'),
  ];
  $info['tokens']['liberty_claims']['plate'] = [
    'name' => t('Placa'),
    'description' => t('Número de placa del vehículo involucrado en el siniestro'),
  ];
  $info['tokens']['liberty_claims']['date'] = [
    'name' => t('Fecha de ocurrencia'),
    'description' => t('Fecha y hora en la que ocurrió el siniestro'),
  ];
  $info['tokens']['liberty_claims']['whereAddress'] = [
    'name' => t('Dirección de ocurrencia'),
    'description' => t('Dirección exacta donde ocurrió el siniestro'),
  ];
  $info['tokens']['liberty_claims']['description'] = [
    'name' => t('Descripción de los hechos'),
    'description' => t('Relato detallado de cómo ocurrió el siniestro, incluyendo lugar, otros involucrados, partes del vehículo dañadas, entre otros detalles'),
  ];
  $info['tokens']['liberty_claims']['lastname'] = [
    'name' => t('Apellido'),
    'description' => t('Apellido del conductor involucrado'),
  ];
  $info['tokens']['liberty_claims']['name'] = [
    'name' => t('Nombre'),
    'description' => t('Nombre del conductor involucrado'),
  ];
  $info['tokens']['liberty_claims']['phone'] = [
    'name' => t('Celular'),
    'description' => t('Número de celular del conductor involucrado'),
  ];
  $info['tokens']['liberty_claims']['PhoneFijo'] = [
    'name' => t('Teléfono Fijo'),
    'description' => t('Número de teléfono fijo del conductor involucrado'),
  ];
  return $info;
}
