<?php

/**
 * @file
 */

use Drupal\Core\Url;

/**
 * @file
 * Hook and preprocess custom .
 */

/**
 * Hook theme settings.
 */
function lib_login_corredores_theme($existing, $type, $theme, $path) {
  return [
    'custom_login_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Hook theme suggestions.
 */
function lib_login_corredores_theme_suggestions($suggestions, $variables) {
  $suggestions['custom_login_form'] = ['template' => 'custom-login-form.html.twig'];
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lib_login_corredores_preprocess_page(&$variables) {
  $current_path2 = Url::fromRoute('<current>')->toString();
  $current_path = \Drupal::service('path.current')->getPath();
  if ($current_path2 === ('/blog')) {
    $variables['#attached']['library'][] = 'lib_login_corredores/linkhome';
  }
  if (isset($variables['node'])) {
    $nodeType = $variables['node']->getType();
    if ($nodeType === 'page_layout') {
      $variables['#attached']['library'][] = 'lib_login_corredores/linkhome';
    }
  }
}
