<?php

/**
 * @file
 */

use Drupal\Core\Url;

/**
 * @file
 * Hook and preprocess custom .
 */

/**
 * Hook theme settings.
 */
function lib_login_corredores_theme($existing, $type, $theme, $path) {
  return [
    'custom_login_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Hook theme suggestions.
 */
function lib_login_corredores_theme_suggestions($suggestions, $variables) {
  $suggestions['custom_login_form'] = ['template' => 'custom-login-form.html.twig'];
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lib_login_corredores_preprocess_page(&$variables) {
  $current_path = Url::fromRoute('<current>')->toString();
  $path_separate = explode('/', trim($current_path));
  if ($current_path === ('/blog') || $path_separate[1] === 'blog') {
    $variables['#attached']['library'][] = 'lib_login_corredores/linkhome';
  }
  if (isset($variables['node'])) {
    $nodeType = $variables['node']->getType();
    if ($nodeType === 'page_layout') {
      if (isset($variables['node']->field_blog_corredores) && $variables['node']->field_blog_corredores->value) {
        $variables['#attached']['library'][] = 'lib_login_corredores/linkhome';
      }
    }
  }
}
