<?php

/**
 * @file
 * lib_cf.module
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_forma_alter().
 */
function lib_cf_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if (strpos($form_id, 'webform_submission_') === 0) {

    $form['#attached']['library'][] = 'lib_cf/captcha';

  }
}

/**
 * Lib cf node access.
 */
function lib_cf_node_access(NodeInterface $node, $op, AccountInterface $account) {

  $node_type = $node->getType();

  if ($node_type == 'informes') {

    // Roles Body Class.
    $userRoles = $account->getRoles();
    // Roles.
    if (in_array('administrator', $userRoles)|| in_array('informes_rol', $userRoles)) {
      return AccessResult::allowed()->cachePerPermissions();
    }
    else {
      return AccessResult::forbidden();
    }
  }
}
