<?php

/**
 * @file
 * Includes the autoloader created by Composer.
 *
<<<<<<< HEAD
 * This file was generated by drupal-composer/drupal-scaffold.
 * https://github.com/drupal-composer/drupal-scaffold
=======
 * This file was generated by drupal-scaffold.
>>>>>>> main
 *
 * @see composer.json
 * @see index.php
 * @see core/install.php
 * @see core/rebuild.php
 * @see core/modules/statistics/statistics.php
 */

return require __DIR__ . '/../vendor/autoload.php';
