<?php

function liberty_core_node_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display)
{

    if ($entity->bundle() == 'campaign') {
        // @todo: Agregar validacion a view mode full
        $build['#cache']['max-age'] = 0;
        \Drupal::service('page_cache_kill_switch')->trigger();

        $moderation_state = $entity->get('moderation_state')->getValue()[0]['value'];
        if ($moderation_state == "archived") {
            header('Location: /not-access');
            exit;

        }

    } elseif ($entity->bundle() == 'webform') {
        // @todo: Agregar validacion a view mode full
        $build['#cache']['max-age'] = 0;
        \Drupal::service('page_cache_kill_switch')->trigger();
    }

}

/**
 * Implements hook_form_alter().
 */
function liberty_core_form_alter(&$form, &$form_state, $form_id)
{

}

function liberty_core_form_submit(array $form, \Drupal\Core\Form\FormStateInterface $form_state)
{
    //die("I'm not getting run, why :(");
    \Drupal::service('messenger')->addMessage("Why won't this message show?");
}
