<?php

/**
 * @file
 * Contains lib_components_v3.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lib_components_v3_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lib_components_v3 module.
    case 'help.page.lib_components_v3':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('version 3 for liberty components') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function lib_components_v3_theme() {
  return [
    'lib_components_v3' => [
      'render element' => 'children',
    ],
  ];
}
/**
* Implements hook_theme_suggestions_block_alter().
*/
function lib_components_v3_theme_suggestions_block_alter(array &$suggestions, array $variables, $hook)
{
   if (isset($variables['elements']['content']['#block_content'])) {
       array_splice($suggestions, 1, 0, 'block__' . $variables['elements']['content']['#block_content']->bundle());
   }
}
